// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/dice.proto

package dice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b299c7e2607893, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Pong struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b299c7e2607893, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Empty1 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty1) Reset()         { *m = Empty1{} }
func (m *Empty1) String() string { return proto.CompactTextString(m) }
func (*Empty1) ProtoMessage()    {}
func (*Empty1) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b299c7e2607893, []int{2}
}

func (m *Empty1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty1.Unmarshal(m, b)
}
func (m *Empty1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty1.Marshal(b, m, deterministic)
}
func (m *Empty1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty1.Merge(m, src)
}
func (m *Empty1) XXX_Size() int {
	return xxx_messageInfo_Empty1.Size(m)
}
func (m *Empty1) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty1.DiscardUnknown(m)
}

var xxx_messageInfo_Empty1 proto.InternalMessageInfo

type Hello struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hello) Reset()         { *m = Hello{} }
func (m *Hello) String() string { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()    {}
func (*Hello) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b299c7e2607893, []int{3}
}

func (m *Hello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hello.Unmarshal(m, b)
}
func (m *Hello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hello.Marshal(b, m, deterministic)
}
func (m *Hello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hello.Merge(m, src)
}
func (m *Hello) XXX_Size() int {
	return xxx_messageInfo_Hello.Size(m)
}
func (m *Hello) XXX_DiscardUnknown() {
	xxx_messageInfo_Hello.DiscardUnknown(m)
}

var xxx_messageInfo_Hello proto.InternalMessageInfo

func (m *Hello) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The request message containing the user's name.
type RollDiceRequest struct {
	Num                  int32    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollDiceRequest) Reset()         { *m = RollDiceRequest{} }
func (m *RollDiceRequest) String() string { return proto.CompactTextString(m) }
func (*RollDiceRequest) ProtoMessage()    {}
func (*RollDiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b299c7e2607893, []int{4}
}

func (m *RollDiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollDiceRequest.Unmarshal(m, b)
}
func (m *RollDiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollDiceRequest.Marshal(b, m, deterministic)
}
func (m *RollDiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollDiceRequest.Merge(m, src)
}
func (m *RollDiceRequest) XXX_Size() int {
	return xxx_messageInfo_RollDiceRequest.Size(m)
}
func (m *RollDiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RollDiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RollDiceRequest proto.InternalMessageInfo

func (m *RollDiceRequest) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

// The response message containing the greetings
type RollDiceResponse struct {
	Dice                 []int32  `protobuf:"varint,1,rep,packed,name=dice,proto3" json:"dice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollDiceResponse) Reset()         { *m = RollDiceResponse{} }
func (m *RollDiceResponse) String() string { return proto.CompactTextString(m) }
func (*RollDiceResponse) ProtoMessage()    {}
func (*RollDiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6b299c7e2607893, []int{5}
}

func (m *RollDiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollDiceResponse.Unmarshal(m, b)
}
func (m *RollDiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollDiceResponse.Marshal(b, m, deterministic)
}
func (m *RollDiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollDiceResponse.Merge(m, src)
}
func (m *RollDiceResponse) XXX_Size() int {
	return xxx_messageInfo_RollDiceResponse.Size(m)
}
func (m *RollDiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RollDiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RollDiceResponse proto.InternalMessageInfo

func (m *RollDiceResponse) GetDice() []int32 {
	if m != nil {
		return m.Dice
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*Pong)(nil), "Pong")
	proto.RegisterType((*Empty1)(nil), "Empty1")
	proto.RegisterType((*Hello)(nil), "Hello")
	proto.RegisterType((*RollDiceRequest)(nil), "RollDiceRequest")
	proto.RegisterType((*RollDiceResponse)(nil), "RollDiceResponse")
}

func init() { proto.RegisterFile("protos/dice.proto", fileDescriptor_d6b299c7e2607893) }

var fileDescriptor_d6b299c7e2607893 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x46, 0x13, 0x2e, 0xbb, 0x89, 0xd3, 0x98, 0x9b, 0xc6, 0x98, 0x2a, 0xae, 0x20, 0x57, 0xad,
	0x44, 0xff, 0x81, 0x28, 0x58, 0x86, 0xc5, 0xca, 0x2e, 0x9e, 0x43, 0x08, 0x6c, 0xb2, 0xb9, 0x9b,
	0xa4, 0xf0, 0xdf, 0x4b, 0x46, 0x0e, 0xe1, 0x8a, 0xeb, 0xde, 0xb2, 0x0f, 0xe6, 0xf1, 0xc1, 0x76,
	0x3a, 0x86, 0x39, 0xf0, 0xe3, 0x77, 0xbf, 0x27, 0x2b, 0x6c, 0x52, 0x50, 0x6f, 0xc3, 0x34, 0xff,
	0x98, 0x0a, 0x92, 0x26, 0x8c, 0x1d, 0x16, 0x90, 0x0e, 0xc4, 0xdc, 0x76, 0x54, 0xc4, 0x55, 0xbc,
	0xbb, 0x72, 0xa7, 0xa7, 0xc9, 0x40, 0x8b, 0x5a, 0x9b, 0x3b, 0x50, 0xef, 0xe4, 0x7d, 0xb8, 0x20,
	0xdf, 0xc3, 0xb5, 0x0b, 0xde, 0xbf, 0xf6, 0x7b, 0x72, 0x74, 0x58, 0x88, 0x67, 0xcc, 0x61, 0x33,
	0x2e, 0x83, 0x88, 0xca, 0xad, 0x68, 0x1e, 0x20, 0xff, 0x97, 0x78, 0x0a, 0x23, 0x13, 0x22, 0x24,
	0x6b, 0x5e, 0x11, 0x57, 0x9b, 0x9d, 0x72, 0xc2, 0x4f, 0x07, 0xc8, 0x3e, 0x96, 0x39, 0x1c, 0xfb,
	0xd6, 0xe3, 0x0d, 0x24, 0x4d, 0x3f, 0x76, 0xa8, 0xad, 0xc4, 0x94, 0xca, 0xae, 0xd9, 0x26, 0xc2,
	0x5b, 0x48, 0x9a, 0x96, 0x19, 0xd3, 0xbf, 0x8f, 0xba, 0xd4, 0x56, 0x22, 0x4d, 0x84, 0x35, 0x64,
	0xa7, 0x3b, 0x98, 0xdb, 0xb3, 0xae, 0x72, 0x6b, 0xcf, 0x23, 0x4c, 0xf4, 0x92, 0x7d, 0x6a, 0x2b,
	0x3b, 0x7d, 0x69, 0x19, 0xea, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x5a, 0x3e, 0x1d, 0x3d,
	0x01, 0x00, 0x00,
}
